### PR TITLE
feat: slack alert manager notification implementation & test & documentation for setting up slack webhook and how to set up climatik to send alerts

### PR DESCRIPTION
**Pull request by zhifanl**
## What has been changed?

- feat: slack alert manager notification implementation & test & documentation for setting up slack webhook and how to set up climatik to send alerts

### CODE REVIEW

**Review by rootfs — APPROVED** [review]

**Comment by rootfs** [comment]
This is great! Thanks for making this happen!

**Comment by zhifanl** [comment]
> This is great! Thanks for making this happen!

my pleasure :) 

I am thinking about we can add an outcoming webhook trigger from slack to update power capping limit / CPU util / Memory Util from slack. This will make users easier to control the power consumption, even without the reach of a laptop: they can do it in slack app from phones.

**Comment by rootfs** [comment]
that's could be something you can try. The webhook should have some built-in security features e.g. only reacting to certain slack ID, etc.

**Comment by rootfs** [comment]
@zhifanl Can you also make a demo video and post it on the README too?

**Comment by zhifanl** [comment]
> @zhifanl Can you also make a demo video and post it on the README too?

sure. I can. But currently the trigger only runs locally, and the CPU & Memory metrics are hard-coded. Tomorrow I will try to finish the query Prometheus' API to check actual metric values and integrate with the slack notification service

**Comment by rootfs** [comment]
i see. We can add more info in the alert, including the past CPU power metrics from Prometheus so the webhook can use that info to help make decisions

**Comment by zhifanl** [comment]
> i see. We can add more info in the alert, including the past CPU power metrics from Prometheus so the webhook can use that info to help make decisions

definitely, will do. I will see if we can generate a small plot embedded in message based on past n minutes/hours CPU power metrics

**Pull request merged**
